url: https://www.washingtoncc.club
baseurl:

# Site settings
title: Washington Cricket Club
email: washingtoncricclub@gmail.com
description: "Based in Redmond, WA. WCC is one of the best emerging cricket clubs across the Pacific Northwest having won both the T20 and T40 Northwest cricket League (NWCL) championships in its inaugral year.

# Postal address (add as many lines as necessary)
address:
  - line: Redmond, WA 98052
  
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag