url: https://washingtoncricclub.github.io
baseurl:

# Site settings
title: Washington Cricket Club
email: washingtoncricclub@gmail.com
description: "An Awesome Cricket CLub."

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty