url: https://www.washingtoncc.club
baseurl:

# Site settings
title: Washington Cricket Club
email: washingtoncricclub@gmail.com
description: "Washington Cricket club (WCC) is based in Redmond, Washington. Formed in 2019, it is one of the best emerging cricket clubs across the Pacific Northwest having won both the T20 and T40 Northwest cricket League (NWCL) championships in its inaugral year.
WCC comprises of passionate, committed and yet easy going cricket enthusiasts which make the game even more enjoyable."

# Postal address (add as many lines as necessary)
address:
  - line: Redmond, WA 98052
  
markdown: kramdown
permalink: pretty